### ISSUE TITLE
Regional microsimulation model

### ISSUE THREAD

**Issue by Robinlovelace** [CatchDat/humanleague#1]
This issue will be complete when:

- [x] We have generated a synthetic dataset for a region
- [x] Demonstrated the method
- [x] Visualised the results

Can split into smaller issues later down the line.

This represents work package 10.3.1.

**Comment by Robinlovelace** [comment]
Newcastle is penciled in as the 'demonstrator' city.

**Comment by virgesmith** [comment]
Single MSOA microsim code commited. 
Next steps: 
- link to TravelAI data
- expand to city-wide area

**Comment by virgesmith** [comment]
City-level microsim code now done (static population). 
Utilises nomisweb RESTful API to streamline getting census data.

**Comment by virgesmith** [comment]
First cut: TravelAI app users now linked to Newcastle synthetic population by OD (MSOA), sex and age band.
NB this is a small number - 17 users (of which 4 do not specify one or more of OD, sex, age band)

**Comment by virgesmith** [comment]
TravelAI app users OD data now visualised (also MSOA boundaries within Newcastle)
