### ISSUE TITLE
National microsimulation model

### ISSUE THREAD

**Issue by Robinlovelace** [CatchDat/humanleague#3]
Demonstrate the software developed for #2 can scale nationally and visualise the results.

**Comment by virgesmith** [comment]
Problem with the size of the query when applied nationally, its ~94000 chars long, and nomisweb rejects it
"Error in curl::curl_download(queryUrl, filename) : HTTP error 414."

**Comment by virgesmith** [comment]
Have now split into multiple queries. Still some issues as nomisweb server appears not to like being bombarded with requests (probably some daily data limit)
