### ISSUE TITLE
Regional microsim - add simulated trips

### ISSUE THREAD

**Issue by virgesmith** [CatchDat/humanleague#8]
Build on static regional microsim #1 by adding trips

**Comment by Robinlovelace** [comment]
Nice one for increasing the effort level - most people would take 1000+ days and still not finish it so an impressive rate of work!

**Comment by virgesmith** [comment]
- Simulated trips to/from work added, using graphhopper API (via stplanr)
- One issue with this is that graphhopper only covers road trips. We need an alternative route provider e.g. OpenTripPlanner that 
- Also graphhopper API limits queries per day quite restricitvely
